CREATE DATABASE PERSONA;
USE PERSONA;

CREATE TABLE PERSONAS
(
	Id INT NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(30) NOT NULL,
	APELLIDOP VARCHAR(30) NOT NULL,
	APELLIDOM VARCHAR(30),
    EMAIL VARCHAR(40) NOT NULL,
    TELEFONO LONG NOT NULL,
    FECHA VARCHAR(10) NOT NULL,
	PRIMARY KEY (Id)
);
DELIMITER //
CREATE PROCEDURE AGREGAR (NOMBRE VARCHAR(30), APELLIDOP VARCHAR(30),APELLIDOM VARCHAR(30),EMAIL VARCHAR(400),TELEFONO LONG,FECHA VARCHAR(10))
BEGIN
INSERT INTO PERSONAS(NOMBRE, APELLIDOP,APELLIDOM,EMAIL,TELEFONO,FECHA) VALUES (NOMBRE,APELLIDOP,APELLIDOM,EMAIL,TELEFONO,FECHA);
END//
DELIMITER ;

DELIMITER //
CREATE PROCEDURE MODIFICAR (ID INT,NOMBRE VARCHAR(30), APELLIDOP VARCHAR(30),APELLIDOM VARCHAR(30),EMAIL VARCHAR(40),TELEFONO LONG,FECHA VARCHAR(10))
BEGIN
UPDATE PERSONAS SET PERSONAS.NOMBRE=NOMBRE, PERSONAS.APELLIDOP=APELLIDOP, PERSONAS.APELLIDOM=APELLIDOM, PERSONAS.EMAIL=EMAIL, PERSONAS.TELEFONO=TELEFONO, PERSONAS.FECHA=FECHA 
WHERE PERSONAS.ID=ID;
END//
DELIMITER ;

DELIMITER //
CREATE PROCEDURE ELIMINAR (ID INT)
BEGIN
DELETE FROM PERSONAS
WHERE PERSONAS.ID=ID;
END//
DELIMITER ;

DELIMITER //
CREATE PROCEDURE LEER (EMAIL VARCHAR(40),TELEFONO LONG)
BEGIN
SELECT * FROM PERSONAS
WHERE PERSONAS.TELEFONO=TELEFONO OR PERSONAS.EMAIL=EMAIL;
END//
DELIMITER ;
SELECT * FROM PERSONAS;

/*
CALL MODIFICAR(2,"ROLANDO","RAMIREZ","HERNANDEZ","ROLANDO.RAHE@GMAIL.COM",8189010673,"01/09/1976");
CALL AGREGAR("SANTIAGO","RAMIREZ","GARCIA","SANTIAGO.RG@LIVE.COM",8112726371,"04/10/2001");
CALL AGREGAR("Y","Y","Y","Y",9,"Y");
CALL MODIFICAR(2,"X","X","X","X",5,"Y");
CALL ELIMINAR(1);
CALL LEER ("X",11);*/
